### ISSUE TITLE
What is the use case for creating worker from a string?

### ISSUE THREAD

**Issue by audunmo** [zevero/worker-create#1]
Hey! Was looking for something like this, neat idea! I've written up a port of it to use`require` imports so that I can use it with browserify. I saw that your code allows for workers to be created from strings of functions, and I'm wondering what the use case for that is? I'm not sure why the user wouldn't just pass in a regular function object.

**Comment by zevero** [comment]
You could load the string via ajax or sockets and execute it (eval style).
I don't use it like this, but someone requested it on Stackoverflow, and it was easy to implement.

**Comment by McFarts** [comment]
So we don't need to use http requests for new files right?
