### ISSUE TITLE
Usage of your library

### ISSUE THREAD

**Issue by felix2016** [zevero/worker-create#3]
I am not experienced with Java script and maybe what I try to accomplish is easy but I haven't succeed yet. I have a partial view in Asp .net and now my application is making an ajax call inside a function called refresh() to render the partial view.

What I would like to do is to call this function refresh() using your worker-create.js which should make the ajax call.
     var worker = Worker.create(function (e) {
                           refresh();
            });

worker.postMessage('some text');

When I put the break point in the code executed by the worker it doesn't stop there and nothing is rendered.
Could you help me?

**Comment by zevero** [comment]
You only need a worker if you have a long calculation (raytracing, simulation, ...), which shall not block the user interface.
You will not need a worker for a simple ajax call.

If you try load code with an ajax call, you may just use the normal way loading the worker.

My worker-create function is mainly to avoid loading extra js code, I use it to deploy a single minified js file...

**Comment by felix2016** [comment]
Thank you. I sorted out
