### ISSUE TITLE
Looking for some help using the library.

### ISSUE THREAD

**Issue by seannybgoode** [zevero/worker-create#4]
Hi there, 

I'm a bit of a javascript novice, but I'm just trying to figure out how to use your library to create a worker with some function. A bit of background, we need to render multiple events to a calendar, but adding more than a 2-3 events results in some noticeable UI freeze. 

We have a bit of code here that adds an event to the calendar, and if that event is recurring, run the worker process to add the rest of the events. 
![image](https://cloud.githubusercontent.com/assets/2761107/24525835/b918468a-1550-11e7-988c-91ebfd1d78a2.png)

However the problem is, I'm getting this error in my debugger:
![image](https://cloud.githubusercontent.com/assets/2761107/24525879/e72f19b8-1550-11e7-9002-0c78b4f904fa.png)

I'm guessing the worker doesn't like the reference to the calendar. Can you recommend a way to reference the calendar?

**Comment by zevero** [comment]
uh ... sorry. I just found your message accidentally ... well I am afraid  workers can only communicate via TextStrings. I dont think it makes sense to create them inside of an event either...
Maybe you could first use createUrl and then initiate as many workers es you need...
... but I cant see, why you need workers for a calender... I use workers for complex calculations taking some minutes, and occasionally sending back status (which I can show on my main page) or the result.
Hope I could help.

**Comment by seannybgoode** [comment]
Well we're doing operations on multiple calendar events into the future. Waiting for those operations to complete makes the UI unresponsive.

At any rate I can revisit this if need be down the road, but we're doing our best with what we have now. You can close this, and thanks for getting back to me :)

**Comment by zevero** [comment]
I failed speeding up multiple highcharts charts with workers ... I guess they can only be used for data crunching...
